---
language: python
sudo: false
matrix:
  include:
    - python: 2.7
      env: PY_VERSION='2.7'
    - python: 3.4
      env: PY_VERSION='3.4'
    - python: 3.5
      env: PY_VERSION='3.5'
    - python: 3.6
      env: PY_VERSION='3.6'
cache:
  directories:
    - ${HOME}/.cache
install:
  - pip install --upgrade nox-automation codecov
script: nox -e "unit_tests(python_version='$PY_VERSION')"
after_success:
  - codecov
